Repository BusHanyang/hybus-genesis, pull requests merged in 2022-08, with the labels that each got.

#4 yarn berry 적용
  .yarnrc.yml
Labels: enhancement, environment

#22 Bugfix after the first release & beta feedback
  index.html
  public/404.html
  public/image/add_white_48dp.svg
  public/image/expand_less_white_48dp.svg
  public/image/github.png
  public/image/leftArrow.png
  src/App.tsx
  src/app/components/Card.tsx
  src/app/components/FullTime.tsx
  src/app/components/Notice.tsx
  src/app/components/fab/fab.scss
  src/app/components/fab/fab.tsx
  src/app/components/lang/i18n.js
  src/app/components/lang/lang.en.json
  src/app/components/lang/lang.ko.json
  src/app/components/modal/modal.tsx
  src/app/components/modal/modalOpen.tsx
  src/app/components/ptr/refreshing-content.tsx
  tailwind.config.js
Labels: bug, enhancement

#26 Adjust screen height when the address bar is shown
  src/App.tsx
  src/main.tsx
Labels: bug
